import type { GalleryItem } from "@/types/gallery";

/**
 * Liste des photos de la galerie (lieu + pays).
 * Images dans public/gallery/. Pour ajouter : déposer dans public/gallery/, puis ajouter une entrée avec src: "/gallery/nom-fichier.jpg".
 * Mettre à jour caption (lieu + pays) pour chaque photo.
 */
export const galleryItems: GalleryItem[] = [
  {
    id: "img-0039",
    src: "/gallery/IMG_0039.compressed.jpg",
    alt: "Caye Caulker, Belize",
    caption: "Caye Caulker, Belize",
  },
  {
    id: "img-0040",
    src: "/gallery/IMG_0040.compressed.jpg",
    alt: "Caye Caulker, Belize",
    caption: "Caye Caulker, Belize",
  },
  {
    id: "img-0041",
    src: "/gallery/IMG_0041.compressed.jpg",
    alt: "Caye Caulker, Belize",
    caption: "Caye Caulker, Belize",
  },
  {
    id: "img-0042",
    src: "/gallery/IMG_0042.compressed.jpg",
    alt: "Caye Caulker, Belize",
    caption: "Caye Caulker, Belize",
  },
  {
    id: "img-0043",
    src: "/gallery/IMG_0043.compressed.jpg",
    alt: "Caye Caulker, Belize",
    caption: "Caye Caulker, Belize",
  },
  {
    id: "img-7460",
    src: "/gallery/IMG_7460.compressed.jpeg",
    alt: "Los Angeles, États-Unis",
    caption: "Los Angeles, États-Unis",
  },
  {
    id: "img-7462",
    src: "/gallery/IMG_7462.compressed.jpeg",
    alt: "Los Angeles, États-Unis",
    caption: "Los Angeles, États-Unis",
  },
  {
    id: "img-7467",
    src: "/gallery/IMG_7467.compressed.jpeg",
    alt: "Los Angeles, États-Unis",
    caption: "Los Angeles, États-Unis",
  },
  {
    id: "img-7471",
    src: "/gallery/IMG_7471.compressed.jpeg",
    alt: "Los Angeles, États-Unis",
    caption: "Los Angeles, États-Unis",
  },
  {
    id: "img-7499",
    src: "/gallery/IMG_7499.compressed.jpeg",
    alt: "Antigua, Guatemala",
    caption: "Antigua, Guatemala",
  },
  {
    id: "img-7507",
    src: "/gallery/IMG_7507.compressed.jpeg",
    alt: "Antigua, Guatemala",
    caption: "Antigua, Guatemala",
  },
  {
    id: "img-7528",
    src: "/gallery/IMG_7528.compressed.jpeg",
    alt: "Acatenango Volcano, Guatemala",
    caption: "Acatenango Volcano, Guatemala",
  },
  {
    id: "img-7545",
    src: "/gallery/IMG_7545.compressed.jpeg",
    alt: "El Fuego Volcano, Guatemala",
    caption: "El Fuego Volcano, Guatemala",
  },
  {
    id: "img-7555",
    src: "/gallery/IMG_7555.compressed.jpeg",
    alt: "El Fuego Volcano, Guatemala",
    caption: "El Fuego Volcano, Guatemala",
  },
  {
    id: "img-7570",
    src: "/gallery/IMG_7570.compressed.jpeg",
    alt: "El Fuego Volcano, Guatemala",
    caption: "El Fuego Volcano, Guatemala",
  },
  {
    id: "img-7609",
    src: "/gallery/IMG_7609.compressed.jpeg",
    alt: "Semuc Champey, Guatemala",
    caption: "Semuc Champey, Guatemala",
  },
  {
    id: "img-7622",
    src: "/gallery/IMG_7622.compressed.jpeg",
    alt: "Semuc Champey, Guatemala",
    caption: "Semuc Champey, Guatemala",
  },
  {
    id: "img-7629",
    src: "/gallery/IMG_7629.compressed.jpeg",
    alt: "Semuc Champey, Guatemala",
    caption: "Semuc Champey, Guatemala",
  },
  {
    id: "img-7632",
    src: "/gallery/IMG_7632.compressed.jpeg",
    alt: "Semuc Champey, Guatemala",
    caption: "Semuc Champey, Guatemala",
  },
  {
    id: "img-7634",
    src: "/gallery/IMG_7634.compressed.jpeg",
    alt: "Semuc Champey, Guatemala",
    caption: "Semuc Champey, Guatemala",
  },
  {
    id: "img-7639",
    src: "/gallery/IMG_7639.compressed.jpeg",
    alt: "Semuc Champey, Guatemala",
    caption: "Semuc Champey, Guatemala",
  },
  {
    id: "img-7653",
    src: "/gallery/IMG_7653.compressed.jpeg",
    alt: "Flores, Guatemala",
    caption: "Flores, Guatemala",
  },
  {
    id: "img-7678",
    src: "/gallery/IMG_7678.compressed.jpeg",
    alt: "Tikal National Park, Guatemala",
    caption: "Tikal National Park, Guatemala",
  },
  {
    id: "img-7680",
    src: "/gallery/IMG_7680.compressed.jpeg",
    alt: "Tikal National Park, Guatemala",
    caption: "Tikal National Park, Guatemala",
  },
  {
    id: "img-7693",
    src: "/gallery/IMG_7693.compressed.jpeg",
    alt: "Tikal National Park, Guatemala",
    caption: "Tikal National Park, Guatemala",
  },
  {
    id: "img-7697",
    src: "/gallery/IMG_7697.compressed.jpeg",
    alt: "Tikal National Park, Guatemala",
    caption: "Tikal National Park, Guatemala",
  },
  {
    id: "img-7707",
    src: "/gallery/IMG_7707.compressed.jpeg",
    alt: "Tikal National Park, Guatemala",
    caption: "Tikal National Park, Guatemala",
  },
  {
    id: "img-7769",
    src: "/gallery/IMG_7769.compressed.jpeg",
    alt: "Caye Caulker, Belize",
    caption: "Caye Caulker, Belize",
  },
  {
    id: "img-7773",
    src: "/gallery/IMG_7773.compressed.jpeg",
    alt: "Belize Barrier Reef, Belize",
    caption: "Belize Barrier Reef, Belize",
  },
  {
    id: "img-7791",
    src: "/gallery/IMG_7791.compressed.jpeg",
    alt: "Belize Barrier Reef, Belize",
    caption: "Belize Barrier Reef, Belize",
  },
  {
    id: "img-7796",
    src: "/gallery/IMG_7796.compressed.jpeg",
    alt: "Great Blue Hole, Belize",
    caption: "Great Blue Hole, Belize",
  },
  {
    id: "img-7808",
    src: "/gallery/IMG_7808.compressed.jpeg",
    alt: "Belize Barrier Reef, Belize",
    caption: "Belize Barrier Reef, Belize",
  },
  {
    id: "img-7825",
    src: "/gallery/IMG_7825.compressed.jpeg",
    alt: "Caye Caulker, Belize",
    caption: "Caye Caulker, Belize",
  },
  {
    id: "img-8202",
    src: "/gallery/IMG_8202.compressed.jpeg",
    alt: "Amazon Rainforest, Brésil",
    caption: "Amazon Rainforest, Brésil",
  },
  {
    id: "img-8234",
    src: "/gallery/IMG_8234.compressed.jpeg",
    alt: "Amazon Rainforest, Brésil",
    caption: "Amazon Rainforest, Brésil",
  },
  {
    id: "img-8241",
    src: "/gallery/IMG_8241.compressed.jpeg",
    alt: "Amazon Rainforest, Brésil",
    caption: "Amazon Rainforest, Brésil",
  },
  {
    id: "img-8244",
    src: "/gallery/IMG_8244.compressed.jpeg",
    alt: "Amazon Rainforest, Brésil",
    caption: "Amazon Rainforest, Brésil",
  },
  {
    id: "img-8249",
    src: "/gallery/IMG_8249.compressed.jpeg",
    alt: "Amazon Rainforest, Brésil",
    caption: "Amazon Rainforest, Brésil",
  },
  {
    id: "img-8265",
    src: "/gallery/IMG_8265.compressed.jpeg",
    alt: "Amazon Rainforest, Brésil",
    caption: "Amazon Rainforest, Brésil",
  },
  {
    id: "img-8283",
    src: "/gallery/IMG_8283.compressed.jpeg",
    alt: "Amazon Rainforest, Brésil",
    caption: "Amazon Rainforest, Brésil",
  },
  {
    id: "img-8302",
    src: "/gallery/IMG_8302.compressed.jpeg",
    alt: "Manaus, Brésil",
    caption: "Manaus, Brésil",
  },
  {
    id: "img-8310",
    src: "/gallery/IMG_8310.compressed.jpeg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-8320",
    src: "/gallery/IMG_8320.compressed.jpeg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-8328",
    src: "/gallery/IMG_8328.compressed.jpeg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-8330",
    src: "/gallery/IMG_8330.compressed.jpeg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-8340",
    src: "/gallery/IMG_8340.compressed.jpeg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-8341",
    src: "/gallery/IMG_8341.compressed.jpeg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-8415",
    src: "/gallery/IMG_8415.compressed.jpeg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-8444",
    src: "/gallery/IMG_8444.compressed.jpeg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-8451",
    src: "/gallery/IMG_8451.compressed.jpeg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-8452",
    src: "/gallery/IMG_8452.compressed.jpeg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-8490",
    src: "/gallery/IMG_8490.compressed.jpeg",
    alt: "Jericoacoara, Brésil",
    caption: "Jericoacoara, Brésil",
  },
  {
    id: "img-8516",
    src: "/gallery/IMG_8516.compressed.jpeg",
    alt: "Jericoacoara, Brésil",
    caption: "Jericoacoara, Brésil",
  },
  {
    id: "img-8527",
    src: "/gallery/IMG_8527.compressed.jpeg",
    alt: "Rio de Janeiro, Brésil",
    caption: "Rio de Janeiro, Brésil",
  },
  {
    id: "img-8529",
    src: "/gallery/IMG_8529.compressed.jpeg",
    alt: "Rio de Janeiro, Brésil",
    caption: "Rio de Janeiro, Brésil",
  },
  {
    id: "img-8551",
    src: "/gallery/IMG_8551.compressed.jpeg",
    alt: "Rio de Janeiro, Brésil",
    caption: "Rio de Janeiro, Brésil",
  },
  {
    id: "img-8569",
    src: "/gallery/IMG_8569.compressed.jpeg",
    alt: "Rio de Janeiro, Brésil",
    caption: "Rio de Janeiro, Brésil",
  },
  {
    id: "img-8575",
    src: "/gallery/IMG_8575.compressed.jpeg",
    alt: "Rio de Janeiro, Brésil",
    caption: "Rio de Janeiro, Brésil",
  },
  {
    id: "img-8591",
    src: "/gallery/IMG_8591.compressed.jpeg",
    alt: "Rio de Janeiro, Brésil",
    caption: "Rio de Janeiro, Brésil",
  },
  {
    id: "img-8695",
    src: "/gallery/IMG_8695.compressed.jpeg",
    alt: "El Fuego Volcano, Guatemala",
    caption: "El Fuego Volcano, Guatemala",
  },
  {
    id: "img-8801",
    src: "/gallery/IMG_8801.compressed.jpeg",
    alt: "Lac du Bourget, France",
    caption: "Lac du Bourget, France",
  },
  {
    id: "img-8818",
    src: "/gallery/IMG_8818.compressed.jpeg",
    alt: "Lac du Bourget, France",
    caption: "Lac du Bourget, France",
  },
  {
    id: "img-8860",
    src: "/gallery/IMG_8860.compressed.jpeg",
    alt: "Annecy, France",
    caption: "Annecy, France",
  },
  {
    id: "img-8870",
    src: "/gallery/IMG_8870.compressed.jpeg",
    alt: "Annecy, France",
    caption: "Annecy, France",
  },
  {
    id: "img-8983",
    src: "/gallery/IMG_8983.compressed.jpeg",
    alt: "Laponie, Finlande",
    caption: "Laponie, Finlande",
  },
  {
    id: "img-9074",
    src: "/gallery/IMG_9074.compressed.jpg",
    alt: "Jericoacoara, Brésil",
    caption: "Jericoacoara, Brésil",
  },
  {
    id: "img-9075",
    src: "/gallery/IMG_9075.compressed.jpg",
    alt: "Jericoacoara, Brésil",
    caption: "Jericoacoara, Brésil",
  },
  {
    id: "img-9076",
    src: "/gallery/IMG_9076.compressed.jpg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-9077",
    src: "/gallery/IMG_9077.compressed.jpg",
    alt: "Lençóis Maranhenses National Park, Brésil",
    caption: "Lençóis Maranhenses National Park, Brésil",
  },
  {
    id: "img-9283",
    src: "/gallery/IMG_9283.compressed.jpeg",
    alt: "Désert de Tatacoa, Colombie",
    caption: "Désert de Tatacoa, Colombie",
  },
  {
    id: "img-9287",
    src: "/gallery/IMG_9287.compressed.jpeg",
    alt: "Désert de Tatacoa, Colombie",
    caption: "Désert de Tatacoa, Colombie",
  },
  {
    id: "img-9310",
    src: "/gallery/IMG_9310.compressed.jpeg",
    alt: "Désert de Tatacoa, Colombie",
    caption: "Désert de Tatacoa, Colombie",
  },
  {
    id: "img-9360",
    src: "/gallery/IMG_9360.compressed.jpeg",
    alt: "Salento, Colombie",
    caption: "Salento, Colombie",
  },
  {
    id: "img-9370",
    src: "/gallery/IMG_9370.compressed.jpeg",
    alt: "Vallée de Cocora, Colombie",
    caption: "Vallée de Cocora, Colombie",
  },
  {
    id: "img-9380",
    src: "/gallery/IMG_9380.compressed.jpeg",
    alt: "Vallée de Cocora, Colombie",
    caption: "Vallée de Cocora, Colombie",
  },
  {
    id: "img-9433",
    src: "/gallery/IMG_9433.compressed.jpeg",
    alt: "Piedra del Peñol, Colombie",
    caption: "Piedra del Peñol, Colombie",
  },
  {
    id: "img-9462",
    src: "/gallery/IMG_9462.compressed.jpeg",
    alt: "Guatapé, Colombie",
    caption: "Guatapé, Colombie",
  },
  {
    id: "img-9525",
    src: "/gallery/IMG_9525.compressed.jpeg",
    alt: "Santa Marta, Colombie",
    caption: "Santa Marta, Colombie",
  },
  {
    id: "img-9540",
    src: "/gallery/IMG_9540.compressed.jpeg",
    alt: "Mendihuaca, Colombie",
    caption: "Mendihuaca, Colombie",
  },
  {
    id: "img-9557",
    src: "/gallery/IMG_9557.compressed.jpeg",
    alt: "Parc National de Tayrona, Colombie",
    caption: "Parc National de Tayrona, Colombie",
  },
  {
    id: "img-9564",
    src: "/gallery/IMG_9564.compressed.jpeg",
    alt: "Amazon Rainforest, Colombie",
    caption: "Amazon Rainforest, Colombie",
  },
  {
    id: "img-9572",
    src: "/gallery/IMG_9572.compressed.jpeg",
    alt: "Parc National de Tayrona, Colombie",
    caption: "Parc National de Tayrona, Colombie",
  },
  {
    id: "img-9611",
    src: "/gallery/IMG_9611.compressed.jpeg",
    alt: "Cartagena, Colombie",
    caption: "Cartagena, Colombie",
  },
  {
    id: "auroras-laponie",
    src: "/gallery/snowmobile-photography-trip-to-hunt-the-auroras_viky_2025-01-01_049_54242165974_o%202.compressed.JPG",
    alt: "Aurores boréales en Laponie",
    caption: "Laponie, Finlande",
  },
];
